### ISSUE TITLE
OPENAI_TOKEN environment variable not found

### ISSUE THREAD

**Issue by banifou** [Hillrunner2008/netbeans-chatgpt#1]
Hi,
I installed the plugin and set the environment variable on my Linux machine. Unfortunately the plugin doesn't recognize it!
Even after restarting the operating system. 
_**echo $OPENAI_TOKEN**_ shows that environment variable is there.

**Comment by Hillrunner2008** [comment]
@banifou - My guess is you had the jvm already running before you defined the environment variable as the jvm is passed these values when the process is spawned (i.e. when netbeans is started). If you restart netbeans and the problem remains then perhaps the environment variable is not actually defined outside the context of the shell you used to echo out the variable.

Generally speaking in linux you would create a new file in /etc/profile.d/ with a line similar to this
```
export OPENAI_TOKEN=your_token_value
```

I will likely adjust the way this value is sources in the future and allow it to be part of a configuration panel inside the application and store it in preferences similar to other netbeans conffiguration, but i took the short cut to keep it simple for now.
