### ISSUE TITLE
java.lang.UnsupportedClassVersionError: com/stackleader/netbeans/chatgpt/ChatTopComponent has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions

### ISSUE THREAD

**Issue by warrenc5** [Hillrunner2008/netbeans-chatgpt#3]
Firstly thanks a million for opensource this plugin. 
You have helped all of us so much already.

I am about to look into the source code. 

I notice you have built with a very recent version of Java - 

Given (I think) that this is a restful client - does it really need to be compiled against anything other than Java8/11 class binaries?

Making tiny changes like this will enable adoptance of the plugin by a much wider audience, for example those behind business firewalls with strict desktop computing policies.

This is just a suggestion.  Thanks again so much for making this plugin.

**Comment by Hillrunner2008** [comment]
i'm certain this code could easily be adjusted to compile with java 11 and probably java 8 if desired. I wasn't being very thoughtful with using jdk17. I also could backport to be compatible to older netbeans versions with just adjusting dependency versions. Its a very valid call out. 

Next time i sit down to add a feature i'll consider some of this Warren. Thank you for the suggestion.

**Comment by mbien** [comment]
you could add `OpenIDE-Module-Java-Dependencies: Java > 17` to the module manifest (note: `>` means `>=` here). This should check the requirement during installation of the plugin, instead of letting it fail later.

**Comment by Chris2011** [comment]
I can reproduce with JDK 14. I would also suggest using JDK 11. 8 Would be also fine but do we have statistics how much people are still using JDK 8? I think latest NetBeans does also not running on JDK 8 anymore, does it? NetBeans needs JDK 11+ to run so we can say just use JDK 11, not 8.

**Comment by Chris2011** [comment]
As I mentioned: https://github.com/apache/netbeans/issues/6486#issuecomment-1734579254. So I would say, minimum 11 or maybe 14 but not higher.

**Comment by jalgaba** [comment]
My vote would be for the lowest LTS that the latest version of Netbeans runs on, which is currently JDK 11.

**Comment by Hillrunner2008** [comment]
I've finally made this change :-)

https://github.com/Hillrunner2008/netbeans-chatgpt/releases/tag/0.0.3

Sorry to be so slow to respond to this very reasonable request.

**Comment by Chris2011** [comment]
Nice, will test it soon :).
