### ISSUE TITLE
Error "OPENAI_TOKEN environnement variable is not defined. Please restart.."

### ISSUE THREAD

**Issue by businesstemple** [Hillrunner2008/netbeans-chatgpt#5]
Hi,

I set the command in the terminal
echo 'export OPENAI_TOKEN=...' >> ~/.bashrc

then i thought to do it in the app folder
echo 'export OPENAI_TOKEN=....' >> /Applications/.bashrc

but still i have this error message
OPENAI_TOKEN environnement variable is not defined. Please restart..

what should i do ?

thanks :)

**Comment by vicricker** [comment]
> Hi,
> 
> I set the command in the terminal echo 'export OPENAI_TOKEN=...' >> ~/.bashrc
> 
> then i thought to do it in the app folder echo 'export OPENAI_TOKEN=....' >> /Applications/.bashrc
> 
> but still i have this error message OPENAI_TOKEN environnement variable is not defined. Please restart..
> 
> what should i do ?
> 
> thanks :)

You probably have to logout and log back in again for that to get set.

In a terminal, type 

`echo $OPENAI_TOKEN`

and make sure it shows your token.

I'm on Linux and have it in .bash_profile.  If you're on Mac, you might have to do it differently.

**Comment by Hillrunner2008** [comment]
https://github.com/Hillrunner2008/netbeans-chatgpt/releases/tag/0.0.3

**Comment by Hillrunner2008** [comment]
I've made it easier in the latest release as it seems many were struggling ...
