### ISSUE TITLE
Add openai key to options

### ISSUE THREAD

**Issue by Chris2011** [Hillrunner2008/netbeans-chatgpt#7]
Everytime I started NetBeans I got distracted from the dialog which asked for the open ai key when I first visited the window and it sticks to my statusbar.

For a better user experience we can use a Notification to let the user know: hey you probably didn't fill in your open ai key, if so click here. The link will lead the user to the options, so the options will show up where they can change/add the key. No distraction at all and I can decide wheter I want to or not. Also I think it is possible to just show the notification when I open the window for ChatGPT. It should also be possible to not restart NetBeans. When I click the ChatGPT again it should reload themself while checking the key and do the init process.

**Comment by KelvinGoldCoast** [comment]
I don't know how to work, I already add the token but still not working.

**Comment by Chris2011** [comment]
@KelvinGoldCoast this is not the right ticket for this. This ticket is just a feature request to change an existing logic. You seems to have a problem. Please create a new ticket with all detailed information that help us to identify the problem. To say it is not working, is not really helpful. Thx.

**Comment by Hillrunner2008** [comment]
I had a line of code clearing preferences (which i used to test), I think i left it in last release so update to 0.0.4 to reduce the repetitive collection of the same key (a regression from the original ENV sourced variable).
